"""
Tests for mloads.py against payloads generated by MATLAB.

    cd +json/readers && python3 -m pytest test_mloads.py -q
    cd +json/readers && python3 test_mloads.py        # no pytest needed

testdata.json is written by `test.gen_reader_testdata` in MATLAB; regenerate it
after any change to the wire format.
"""

import json
import math
import os
import warnings

import numpy as np

try:
    import pytest
except ImportError:  # pytest is optional; `python3 test_mloads.py` still works
    class _Approx:
        def __init__(self, v, tol=1e-9):
            self.v, self.tol = v, tol

        def __eq__(self, other):
            return abs(float(other) - float(self.v)) <= self.tol * max(
                1.0, abs(float(self.v))
            )

    class _Warns:
        def __init__(self, _category, match=None):
            self.match = match

        def __enter__(self):
            self.ctx = warnings.catch_warnings(record=True)
            self.log = self.ctx.__enter__()
            warnings.simplefilter("always")
            return self.log

        def __exit__(self, *exc):
            self.ctx.__exit__(*exc)
            if exc[0] is not None:
                return False
            texts = [str(w.message) for w in self.log]
            assert texts, "expected a warning, got none"
            if self.match is not None:
                assert any(self.match in t for t in texts), \
                    "no warning matching %r in %r" % (self.match, texts)
            return False

    class _Mark:
        @staticmethod
        def parametrize(_names, _values):
            return lambda fn: fn

    class pytest:  # noqa: N801  (stand-in for the real module)
        approx = staticmethod(lambda v, **kw: _Approx(v, **kw))
        warns = _Warns
        mark = _Mark

from mloads import mloads

HERE = os.path.dirname(os.path.abspath(__file__))
_NUMERIC = {
    "double", "single", "logical",
    "int8", "uint8", "int16", "uint16", "int32", "uint32", "int64", "uint64",
}


def load_cases():
    with open(os.path.join(HERE, "testdata.json")) as fh:
        return {c["name"]: c for c in json.load(fh)["cases"]}


CASES = load_cases()


def decode(name):
    assert name in CASES, "no payload named %r; regenerate testdata.json" % name
    return mloads(CASES[name]["payload"])


# --- the bug this format exists to prevent ------------------------------
# Leaves are stored column-major. Reshaping with NumPy's default C order
# silently transposes, which is why mloads passes order="F".

def test_matrix_2d_is_not_transposed():
    # MATLAB reshape(1:6, 2, 3) is [1 3 5; 2 4 6]
    got = decode("matrix_2d")
    assert got.shape == (2, 3)
    np.testing.assert_array_equal(got, [[1, 3, 5], [2, 4, 6]])


def test_matrix_3d_ordering():
    got = decode("matrix_3d")
    assert got.shape == (2, 3, 4)
    # MATLAB fills the first dimension fastest
    assert got[0, 0, 0] == 1
    assert got[1, 0, 0] == 2
    assert got[0, 1, 0] == 3
    assert got[0, 0, 1] == 7
    assert got[1, 2, 3] == 24


def test_column_and_row_vectors_keep_orientation():
    assert decode("row_vector").shape == (1, 10)
    assert decode("col_vector").shape == (10, 1)


# --- scalars and classes ------------------------------------------------

def test_scalars():
    assert decode("double_scalar") == pytest.approx(math.pi)
    assert decode("logical_true") is True
    assert decode("logical_false") is False
    assert decode("int8_scalar") == -128
    assert decode("uint8_scalar") == 255


def test_int64_beyond_double_precision_is_exact():
    # 2**62 + 12345 is not representable as a float64
    assert decode("int64_big") == 2**62 + 12345
    assert decode("uint64_big") == 2**64 - 1
    assert decode("int64_min") == -(2**63)


def test_dtypes_survive():
    assert decode("single_matrix").dtype == np.float32
    assert decode("uint8_matrix").dtype == np.uint8
    assert decode("logical_array").dtype == np.bool_


# --- non-finite values --------------------------------------------------

def test_nonfinite_are_distinguished():
    got = decode("nonfinite_mix")           # [1 NaN Inf -Inf 2]
    flat = got.reshape(-1, order="F")
    assert flat[0] == 1
    assert math.isnan(flat[1])
    assert flat[2] == math.inf
    assert flat[3] == -math.inf
    assert flat[4] == 2


def test_nonfinite_scalars():
    assert math.isnan(decode("nan_scalar"))
    assert decode("inf_scalar") == math.inf
    assert decode("neginf_scalar") == -math.inf


def test_all_nan_vector():
    got = decode("all_nan_vector")
    assert got.shape == (1, 3)
    assert all(math.isnan(x) for x in got.reshape(-1))


# --- char and string ----------------------------------------------------

def test_char_row_is_a_string():
    assert decode("char_row") == "a char array"
    assert decode("char_single") == "x"
    assert decode("empty_char") == ""


def test_char_matrix_comes_back_as_rows():
    assert decode("char_matrix") == ["abc", "def"]


def test_char_with_awkward_content():
    assert decode("char_with_quotes") == 'he said "hi" and \\ backslash'
    assert decode("char_unicode") == "naïve café αβγ 日本語"
    # v1 corrupted this by rewriting the literal NaN inside the string
    assert decode("char_nan_literal") == "the value is NaN and Infinity"
    assert decode("char_json_looking") == '{"vals":1,"info":2}'


def test_string_arrays():
    assert decode("string_scalar") == "hello"
    assert decode("string_array") == ["a", "bb", "ccc"]


# --- containers ---------------------------------------------------------

def test_cells():
    assert decode("cell_scalars") == [1.0, 2.0, 3.0]
    assert decode("cell_strings") == ["one", "two", "three"]
    assert decode("empty_cell") == []
    assert decode("cell_of_cells") == [[1.0, 2.0], [3.0, 4.0]]
    assert decode("cell_of_cell_cells") == [[[1.0, 2.0], [3.0, 4.0]],
                                            [[5.0, 6.0], [7.0, 8.0]]]


def test_cell_mixed_preserves_each_element_type():
    got = decode("cell_mixed")   # {1, 'ab', [1 2 3], {4, 5}, struct('a',1), true}
    assert got[0] == 1.0
    assert got[1] == "ab"
    np.testing.assert_array_equal(got[2], [[1, 2, 3]])
    assert got[3] == [4.0, 5.0]
    assert got[4] == {"a": 1.0}
    assert got[5] is True


def test_structs():
    assert decode("struct_simple") == {"a": 1.0, "b": 2.0}
    assert decode("struct_no_fields") == {}
    # a field literally named type__ collided with v1's metadata sentinel
    got = decode("struct_field_type__")
    assert got["type__"] == "collides with v1 sentinel"


def test_struct_field_order_is_preserved():
    assert list(decode("struct_readme").keys()) == ["foo", "bar", "nerf"]


def test_nested_struct():
    got = decode("struct_readme")
    assert got["foo"] == 1.0
    assert got["bar"]["t"].shape == (10, 10)
    assert got["bar"]["d"] == "a char array"
    np.testing.assert_array_equal(got["nerf"], [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])


def test_struct_arrays():
    assert decode("struct_arr_1x3") == [{"a": 1.0}, {"a": 2.0}, {"a": 3.0}]
    assert decode("struct_arr_2fields") == [{"a": 1.0, "b": "x"},
                                            {"a": 2.0, "b": "yy"}]
    # 2x3 struct array flattens column-major
    assert [d["v"] for d in decode("struct_arr_2x3")] == [1.0, 2.0, 3.0, 4.0, 5.0, 6.0]


def test_empty_struct_with_fields():
    assert decode("empty_struct_fields") == []


def test_combo_struct_of_struct_array():
    got = decode("combo_3")
    trials = got["trials"]
    assert len(trials) == 3
    assert trials[0]["rt"] == pytest.approx(0.3)
    assert math.isnan(trials[1]["rt"])
    assert trials[0]["ok"] is True
    assert trials[1]["ok"] is False
    assert [t["tag"] for t in trials] == ["a", "bb", ""]


# --- plain-JSON readability, the property the format is built around ----

def test_vals_is_usable_without_info():
    """A reader that ignores `info` still gets sensible data."""
    raw = json.loads(CASES["struct_readme"]["payload"])
    vals = raw["vals"]
    assert vals["foo"] == 1
    assert vals["bar"]["d"] == "a char array"
    assert len(vals["bar"]["t"]) == 100      # flat, but present and correct
    assert vals["nerf"] == [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


def test_legacy_payload_warns_and_returns_vals():
    legacy = '{"vals":[1,2,3,4,5,6],"info":{"type__":"uint8","dim__":[3,2]}}'
    with pytest.warns(UserWarning, match="format-1"):
        assert mloads(legacy) == [1, 2, 3, 4, 5, 6]


# --- broad coverage: every payload decodes with the right root shape ----

@pytest.mark.parametrize("name", sorted(CASES))
def test_every_payload_decodes(name):
    case = CASES[name]
    got = mloads(case["payload"])
    dims = tuple(int(d) for d in case["dims"])
    n = 1
    for d in dims:
        n *= d

    if case["class"] in _NUMERIC:
        if n == 1:
            assert isinstance(got, (float, int, bool))
        else:
            assert isinstance(got, np.ndarray)
            assert got.shape == dims
    elif case["class"] in ("cell", "struct"):
        if case["class"] == "struct" and n == 1:
            assert isinstance(got, dict)
        else:
            assert isinstance(got, list)
            assert len(got) == n
    elif case["class"] == "char":
        assert isinstance(got, (str, list))
    elif case["class"] == "string":
        assert isinstance(got, (str, list))


def main():
    """Run without pytest: exercise every test function in this module."""
    import traceback

    fns = [(k, v) for k, v in sorted(globals().items())
           if k.startswith("test_") and callable(v)]
    npass = nfail = 0
    for name, fn in fns:
        targets = [(name, ())]
        if name == "test_every_payload_decodes":
            targets = [(name, (c,)) for c in sorted(CASES)]
        for label, argv in targets:
            try:
                fn(*argv)
                npass += 1
            except Exception:
                nfail += 1
                print("FAIL %s%s" % (label, argv if argv else ""))
                traceback.print_exc()
    print("\n%d passed, %d failed" % (npass, nfail))
    raise SystemExit(1 if nfail else 0)


if __name__ == "__main__":
    main()
