# Tests for mloads.R against payloads generated by MATLAB.
#
#   Rscript test_mloads.R
#
# Uses a tiny assertion helper rather than testthat so it runs with base R plus
# jsonlite. testdata.json is written by `test.gen_reader_testdata` in MATLAB;
# regenerate it after any change to the wire format.

# Resolve this script's directory so the suite runs from anywhere: --file= is
# what Rscript passes, ofile is what source() sets.
.script_dir <- function() {
  a <- grep("^--file=", commandArgs(trailingOnly = FALSE), value = TRUE)
  if (length(a) == 1L) return(dirname(normalizePath(sub("^--file=", "", a))))
  of <- tryCatch(sys.frame(1)$ofile, error = function(e) NULL)
  if (!is.null(of)) return(dirname(normalizePath(of)))
  getwd()
}
here <- .script_dir()
source(file.path(here, "mloads.R"))

NUMERIC <- c("double", "single", "logical", "int8", "uint8", "int16", "uint16",
             "int32", "uint32", "int64", "uint64")

doc <- jsonlite::fromJSON(file.path(here, "testdata.json"), simplifyVector = FALSE)
CASES <- setNames(doc$cases, vapply(doc$cases, function(c) c$name, character(1)))

npass <- 0L
nfail <- 0L

expect <- function(label, cond) {
  ok <- isTRUE(tryCatch(cond, error = function(e) {
    message("  ERROR in ", label, ": ", conditionMessage(e))
    FALSE
  }))
  if (ok) {
    npass <<- npass + 1L
  } else {
    nfail <<- nfail + 1L
    cat("FAIL:", label, "\n")
  }
}

decode <- function(name) {
  stopifnot(name %in% names(CASES))
  suppressWarnings(mloads(CASES[[name]]$payload))
}

# --- the bug this format exists to prevent ------------------------------
# Leaves are stored column-major, which is R's own array order, so array()
# is correct as written. Getting this wrong transposes silently.

got <- decode("matrix_2d")                  # MATLAB reshape(1:6,2,3)
expect("matrix_2d dims", identical(dim(got), c(2L, 3L)))
expect("matrix_2d not transposed", isTRUE(all.equal(got, matrix(as.numeric(1:6), nrow = 2))))
expect("matrix_2d values", got[1, 2] == 3 && got[2, 1] == 2)

got3 <- decode("matrix_3d")
expect("matrix_3d dims", identical(dim(got3), c(2L, 3L, 4L)))
expect("matrix_3d order", got3[1, 1, 1] == 1 && got3[2, 1, 1] == 2 &&
                          got3[1, 2, 1] == 3 && got3[1, 1, 2] == 7 &&
                          got3[2, 3, 4] == 24)

expect("row_vector dims", identical(dim(decode("row_vector")), c(1L, 10L)))
expect("col_vector dims", identical(dim(decode("col_vector")), c(10L, 1L)))

# --- scalars and classes ------------------------------------------------

expect("double_scalar", isTRUE(all.equal(decode("double_scalar"), pi)))
expect("logical_true", identical(decode("logical_true"), TRUE))
expect("logical_false", identical(decode("logical_false"), FALSE))
expect("int8_scalar", decode("int8_scalar") == -128)
expect("uint8_scalar", decode("uint8_scalar") == 255)
expect("logical_array is logical", is.logical(decode("logical_array")))
expect("logical_array values",
       identical(as.vector(decode("logical_array")),
                 c(TRUE, FALSE, FALSE, TRUE, TRUE, FALSE)))

# R has no native 64-bit integer, so these are doubles and warn about it.
expect("int64_big warns", {
  w <- tryCatch({ mloads(CASES[["int64_big"]]$payload); NULL },
                warning = function(w) conditionMessage(w))
  !is.null(w) && grepl("precision", w)
})
expect("int64_big approx", abs(decode("int64_big") - 2^62) < 2^20)

# --- non-finite values --------------------------------------------------

flat <- as.vector(decode("nonfinite_mix"))   # [1 NaN Inf -Inf 2]
expect("nonfinite 1", flat[1] == 1)
expect("nonfinite NaN", is.nan(flat[2]))
expect("nonfinite Inf", flat[3] == Inf)
expect("nonfinite -Inf", flat[4] == -Inf)
expect("nonfinite 2", flat[5] == 2)

expect("nan_scalar", is.nan(decode("nan_scalar")))
expect("inf_scalar", decode("inf_scalar") == Inf)
expect("neginf_scalar", decode("neginf_scalar") == -Inf)
expect("all_nan_vector", all(is.nan(as.vector(decode("all_nan_vector")))))

# --- char and string ----------------------------------------------------

expect("char_row", identical(decode("char_row"), "a char array"))
expect("char_single", identical(decode("char_single"), "x"))
expect("empty_char", identical(decode("empty_char"), ""))
expect("char_matrix rows", identical(decode("char_matrix"), c("abc", "def")))
expect("char_with_quotes",
       identical(decode("char_with_quotes"), 'he said "hi" and \\ backslash'))
expect("char_unicode", identical(decode("char_unicode"), "naïve café αβγ 日本語"))
# v1 corrupted this by rewriting the literal NaN inside the string
expect("char_nan_literal",
       identical(decode("char_nan_literal"), "the value is NaN and Infinity"))
expect("char_json_looking",
       identical(decode("char_json_looking"), '{"vals":1,"info":2}'))
expect("string_scalar", identical(decode("string_scalar"), "hello"))
expect("string_array", identical(decode("string_array"), c("a", "bb", "ccc")))

# --- containers ---------------------------------------------------------

expect("cell_scalars", identical(decode("cell_scalars"), list(1, 2, 3)))
expect("cell_strings", identical(decode("cell_strings"), list("one", "two", "three")))
expect("empty_cell", identical(decode("empty_cell"), list()))
expect("cell_of_cells", identical(decode("cell_of_cells"),
                                  list(list(1, 2), list(3, 4))))
expect("cell_of_cell_cells",
       identical(decode("cell_of_cell_cells"),
                 list(list(list(1, 2), list(3, 4)), list(list(5, 6), list(7, 8)))))

mixed <- decode("cell_mixed")      # {1, 'ab', [1 2 3], {4, 5}, struct('a',1), true}
expect("cell_mixed 1", mixed[[1]] == 1)
expect("cell_mixed ab", identical(mixed[[2]], "ab"))
expect("cell_mixed vec", identical(as.vector(mixed[[3]]), c(1, 2, 3)))
expect("cell_mixed cell", identical(mixed[[4]], list(4, 5)))
expect("cell_mixed struct", identical(mixed[[5]], list(a = 1)))
expect("cell_mixed logical", identical(mixed[[6]], TRUE))

expect("struct_simple", identical(decode("struct_simple"), list(a = 1, b = 2)))
expect("struct_no_fields", identical(decode("struct_no_fields"), list()))
# a field literally named type__ collided with v1's metadata sentinel
expect("struct_field_type__",
       identical(decode("struct_field_type__")$type__, "collides with v1 sentinel"))
expect("struct field order preserved",
       identical(names(decode("struct_readme")), c("foo", "bar", "nerf")))

readme <- decode("struct_readme")
expect("nested foo", readme$foo == 1)
expect("nested t dims", identical(dim(readme$bar$t), c(10L, 10L)))
expect("nested d", identical(readme$bar$d, "a char array"))
expect("nested nerf", identical(as.vector(readme$nerf), as.numeric(1:10)))

expect("struct_arr_1x3",
       identical(decode("struct_arr_1x3"), list(list(a = 1), list(a = 2), list(a = 3))))
expect("struct_arr_2fields",
       identical(decode("struct_arr_2fields"),
                 list(list(a = 1, b = "x"), list(a = 2, b = "yy"))))
expect("struct_arr_2x3 column-major",
       identical(vapply(decode("struct_arr_2x3"), function(d) d$v, numeric(1)),
                 as.numeric(1:6)))
expect("empty_struct_fields", identical(decode("empty_struct_fields"), list()))

trials <- decode("combo_3")$trials
expect("combo_3 length", length(trials) == 3)
expect("combo_3 rt", isTRUE(all.equal(trials[[1]]$rt, 0.3)))
expect("combo_3 nan rt", is.nan(trials[[2]]$rt))
expect("combo_3 ok", identical(trials[[1]]$ok, TRUE) && identical(trials[[2]]$ok, FALSE))
expect("combo_3 tags",
       identical(vapply(trials, function(t) t$tag, character(1)), c("a", "bb", "")))

# --- plain-JSON readability, the property the format is built around ----

vals <- jsonlite::fromJSON(CASES[["struct_readme"]]$payload,
                           simplifyVector = FALSE)$vals
expect("vals usable without info: foo", vals$foo == 1)
expect("vals usable without info: d", identical(vals$bar$d, "a char array"))
expect("vals usable without info: t", length(vals$bar$t) == 100)
expect("vals usable without info: nerf",
       identical(unlist(vals$nerf), 1:10))

expect("legacy payload warns", {
  legacy <- '{"vals":[1,2,3,4,5,6],"info":{"type__":"uint8","dim__":[3,2]}}'
  w <- tryCatch({ mloads(legacy); NULL },
                warning = function(w) conditionMessage(w))
  !is.null(w) && grepl("format-1", w)
})

# --- broad coverage: every payload decodes with the right root shape ----

for (name in sort(names(CASES))) {
  case <- CASES[[name]]
  got <- suppressWarnings(mloads(case$payload))
  dims <- as.integer(unlist(case$dims))
  n <- prod(dims)
  cls <- case$class

  if (cls %in% NUMERIC) {
    if (n == 1) {
      expect(paste0(name, ": scalar"), length(got) == 1)
    } else {
      expect(paste0(name, ": dims"), identical(dim(got), dims))
    }
  } else if (cls == "struct") {
    if (n == 1) {
      expect(paste0(name, ": named list"), is.list(got))
    } else {
      expect(paste0(name, ": list of ", n), is.list(got) && length(got) == n)
    }
  } else if (cls == "cell") {
    expect(paste0(name, ": cell list"), is.list(got) && length(got) == n)
  } else if (cls %in% c("char", "string")) {
    expect(paste0(name, ": character"), is.character(got))
  }
}

# --- guards on payloads this reader does not implement -----------------

pay <- function(info, vals, extra = "") {
  paste0('{"fmt":2', extra, ',"vals":', vals, ',"info":[', info, ']}')
}

expect_error <- function(label, text) {
  threw <- tryCatch({ suppressWarnings(mloads(text)); FALSE },
                    error = function(e) TRUE)
  expect(label, threw)
}

# order is what stands between this reader and a silent transpose
expect_error("rejects order=C",
             pay('{"p":[],"t":"double","d":[2,3]}', "[1,2,3,4,5,6]", ',"order":"C"'))
expect_error("rejects base=0",
             pay('{"p":[],"t":"double","d":[1,1]}', "1", ',"base":0'))
# char/string leaves must not silently become empty strings
expect_error("rejects non-string char leaf",
             pay('{"p":[],"t":"char","d":[2,2]}', "42"))
expect_error("rejects non-string in string leaf",
             pay('{"p":[],"t":"string","d":[1,2]}', '["a",7]'))

# nf only means anything for the float classes; it used to leave NaN sitting
# inside an array that info declares to be int32
expect("nf ignored on an integer leaf", {
  got <- suppressWarnings(mloads(
    pay('{"p":[],"t":"int32","d":[1,1],"nf":{"i":1,"k":["NaN"]}}', "[0]")))
  identical(as.numeric(got), 0)
})
# a null in an integer leaf means zero, as MATLAB's cast(NaN,'int32') gives
expect("null in an integer leaf is zero", {
  got <- suppressWarnings(mloads(pay('{"p":[],"t":"uint8","d":[1,2]}', "[null,7]")))
  identical(as.vector(got), c(0, 7))
})
# an nf record wrapped in a one-element array must not drop the Inf
expect("wrapped nf record still applies", {
  got <- suppressWarnings(mloads(pay(
    '{"p":[],"t":"double","d":[1,1],"nf":[{"i":1,"k":["Inf"]}]}', "[null]")))
  identical(as.numeric(got), Inf)
})
# jsonencode writes a one-element array as a bare scalar
expect("scalar dims normalised", {
  identical(as.numeric(suppressWarnings(mloads(
    pay('{"p":[],"t":"double","d":1}', "1")))), 1)
})

# --- metadata ----------------------------------------------------------

m <- suppressWarnings(mloads(CASES[["struct_readme"]]$payload, with_meta = TRUE))
expect("with_meta returns value and meta",
       all(c("value", "meta") %in% names(m)))
expect("with_meta root class", identical(m$meta[[1]]$class, "struct"))
expect("with_meta dims", identical(m$meta[[4]]$dims, c(10L, 10L)))

# --- value checks for the riskier non-finite paths --------------------

sg <- as.vector(decode("single_nonfinite"))    # single([NaN Inf -Inf 1.5])
expect("single_nonfinite NaN", is.nan(sg[1]))
expect("single_nonfinite Inf", sg[2] == Inf)
expect("single_nonfinite -Inf", sg[3] == -Inf)
expect("single_nonfinite value", isTRUE(all.equal(sg[4], 1.5)))

nm <- decode("nan_matrix")                     # [1 NaN; Inf -Inf]
expect("nan_matrix dims", identical(dim(nm), c(2L, 2L)))
expect("nan_matrix values",
       nm[1, 1] == 1 && is.nan(nm[1, 2]) && nm[2, 1] == Inf && nm[2, 2] == -Inf)

cat("\n", npass, " passed, ", nfail, " failed\n", sep = "")
if (nfail > 0) quit(status = 1)
