# Tests for mloads.jl against payloads generated by MATLAB.
#
#   julia --project=. test_mloads.jl          # with JSON or JSON3 available
#
# testdata.json is written by `test.gen_reader_testdata` in MATLAB; regenerate
# it after any change to the wire format.

using Test
using JSON

include("mloads.jl")
using .MLoads

const HERE = @__DIR__
const NUMERIC = Set(["double", "single", "logical", "int8", "uint8", "int16",
                     "uint16", "int32", "uint32", "int64", "uint64"])

raw = JSON.parse(read(joinpath(HERE, "testdata.json"), String))
const CASES = Dict(String(c["name"]) => c for c in raw["cases"])

"""Decode one named payload from the generated test data."""
function decode(name::AbstractString)
    haskey(CASES, name) || error("no payload named $name; regenerate testdata.json")
    mloads(JSON.parse(String(CASES[name]["payload"])))
end

@testset "mloads.jl" begin

    # --- the bug this format exists to prevent --------------------------
    # Leaves are stored column-major, which is Julia's own order, so reshape
    # is correct as written. Getting this wrong transposes silently.
    @testset "shape and order" begin
        got = decode("matrix_2d")             # MATLAB reshape(1:6,2,3)
        @test size(got) == (2, 3)
        @test got == [1 3 5; 2 4 6]

        got3 = decode("matrix_3d")
        @test size(got3) == (2, 3, 4)
        @test got3[1, 1, 1] == 1
        @test got3[2, 1, 1] == 2
        @test got3[1, 2, 1] == 3
        @test got3[1, 1, 2] == 7
        @test got3[2, 3, 4] == 24

        @test size(decode("row_vector")) == (1, 10)
        @test size(decode("col_vector")) == (10, 1)
    end

    @testset "scalars and types" begin
        @test decode("double_scalar") ≈ pi
        @test decode("logical_true") === true
        @test decode("logical_false") === false
        @test decode("int8_scalar") === Int8(-128)
        @test decode("uint8_scalar") === UInt8(255)
        @test eltype(decode("single_matrix")) == Float32
        @test eltype(decode("uint8_matrix")) == UInt8
        @test eltype(decode("logical_array")) == Bool
    end

    @testset "64-bit integers stay exact" begin
        @test decode("int64_big") == Int64(2)^62 + 12345
        @test decode("uint64_big") == typemax(UInt64)
        @test decode("int64_min") == typemin(Int64)
    end

    @testset "non-finite values are distinguished" begin
        flat = vec(decode("nonfinite_mix"))    # [1 NaN Inf -Inf 2]
        @test flat[1] == 1
        @test isnan(flat[2])
        @test flat[3] == Inf
        @test flat[4] == -Inf
        @test flat[5] == 2

        @test isnan(decode("nan_scalar"))
        @test decode("inf_scalar") == Inf
        @test decode("neginf_scalar") == -Inf
        @test all(isnan, vec(decode("all_nan_vector")))
    end

    @testset "char and string" begin
        @test decode("char_row") == "a char array"
        @test decode("char_single") == "x"
        @test decode("empty_char") == ""
        @test decode("char_matrix") == ["abc", "def"]
        @test decode("char_with_quotes") == "he said \"hi\" and \\ backslash"
        @test decode("char_unicode") == "naïve café αβγ 日本語"
        # v1 corrupted this by rewriting the literal NaN inside the string
        @test decode("char_nan_literal") == "the value is NaN and Infinity"
        @test decode("char_json_looking") == "{\"vals\":1,\"info\":2}"
        @test decode("string_scalar") == "hello"
        @test decode("string_array") == ["a", "bb", "ccc"]
    end

    @testset "cells" begin
        @test decode("cell_scalars") == [1.0, 2.0, 3.0]
        @test decode("cell_strings") == ["one", "two", "three"]
        @test decode("empty_cell") == []
        @test decode("cell_of_cells") == [[1.0, 2.0], [3.0, 4.0]]
        @test decode("cell_of_cell_cells") ==
              [[[1.0, 2.0], [3.0, 4.0]], [[5.0, 6.0], [7.0, 8.0]]]

        mixed = decode("cell_mixed")   # {1, 'ab', [1 2 3], {4, 5}, struct, true}
        @test mixed[1] == 1.0
        @test mixed[2] == "ab"
        @test vec(mixed[3]) == [1.0, 2.0, 3.0]
        @test mixed[4] == [4.0, 5.0]
        @test mixed[5] == Dict("a" => 1.0)
        @test mixed[6] === true
    end

    @testset "structs" begin
        @test decode("struct_simple") == Dict("a" => 1.0, "b" => 2.0)
        @test decode("struct_no_fields") == Dict{String,Any}()
        # a field literally named type__ collided with v1's metadata sentinel
        @test decode("struct_field_type__")["type__"] == "collides with v1 sentinel"

        readme = decode("struct_readme")
        @test readme["foo"] == 1.0
        @test size(readme["bar"]["t"]) == (10, 10)
        @test readme["bar"]["d"] == "a char array"
        @test vec(readme["nerf"]) == collect(1.0:10.0)
    end

    @testset "struct arrays" begin
        @test decode("struct_arr_1x3") ==
              [Dict("a" => 1.0), Dict("a" => 2.0), Dict("a" => 3.0)]
        @test decode("struct_arr_2fields") ==
              [Dict("a" => 1.0, "b" => "x"), Dict("a" => 2.0, "b" => "yy")]
        @test [d["v"] for d in decode("struct_arr_2x3")] == [1.0, 2.0, 3.0, 4.0, 5.0, 6.0]
        @test decode("empty_struct_fields") == Dict{String,Any}[]

        trials = decode("combo_3")["trials"]
        @test length(trials) == 3
        @test trials[1]["rt"] ≈ 0.3
        @test isnan(trials[2]["rt"])
        @test trials[1]["ok"] === true
        @test trials[2]["ok"] === false
        @test [t["tag"] for t in trials] == ["a", "bb", ""]
    end

    # --- plain-JSON readability, the property the format is built around
    @testset "vals is usable without info" begin
        vals = JSON.parse(String(CASES["struct_readme"]["payload"]))["vals"]
        @test vals["foo"] == 1
        @test vals["bar"]["d"] == "a char array"
        @test length(vals["bar"]["t"]) == 100
        @test vals["nerf"] == collect(1:10)
    end

    @testset "legacy payload warns and returns vals" begin
        legacy = "{\"vals\":[1,2,3,4,5,6],\"info\":{\"type__\":\"uint8\",\"dim__\":[3,2]}}"
        got = @test_logs (:warn, r"format-1") mloads(JSON.parse(legacy))
        @test got == [1, 2, 3, 4, 5, 6]
    end

    # --- broad coverage: every payload decodes with the right root shape
    @testset "every payload decodes" begin
        for name in sort(collect(keys(CASES)))
            case = CASES[name]
            got = mloads(JSON.parse(String(case["payload"])))
            dims = Int.(case["dims"])
            n = prod(dims)
            cls = String(case["class"])

            if cls in NUMERIC
                if n == 1
                    @test got isa Number
                else
                    @test size(got) == Tuple(dims)
                end
            elseif cls == "struct"
                @test (n == 1) ? (got isa AbstractDict) :
                      (got isa AbstractVector && length(got) == n)
            elseif cls == "cell"
                @test got isa AbstractVector && length(got) == n
            elseif cls in ("char", "string")
                @test got isa Union{AbstractString,AbstractVector}
            end
        end
    end

end
